# Generated by Django 6.0.4 on 2026-06-13 04:38

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Ambulance Service', max_length=140)),
                ('ambulance_phone', models.CharField(blank=True, max_length=30)),
                ('availability_text', models.CharField(blank=True, max_length=160)),
                ('service_area', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ambulance info',
                'verbose_name_plural': 'Ambulance info',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional short icon label or CSS icon name.', max_length=80)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='departments/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('services_list', models.TextField(blank=True, help_text='One service per line.')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Emergency Service', max_length=140)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('availability_text', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Emergency info',
                'verbose_name_plural': 'Emergency info',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='facilities/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCampUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='updates/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
            ],
            options={
                'verbose_name': 'Health camp update',
                'verbose_name_plural': 'Health camp updates',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='doctors/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('qualification', models.CharField(blank=True, max_length=180)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('short_bio', models.TextField(blank=True)),
                ('opd_days_text', models.CharField(blank=True, max_length=160)),
                ('opd_time_text', models.CharField(blank=True, max_length=160)),
                ('appointment_enabled', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospital.department')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPDTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('days', models.CharField(max_length=160)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room_or_location', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_timings', to='hospital.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_timings', to='hospital.doctor')),
            ],
            options={
                'verbose_name': 'OPD timing',
                'verbose_name_plural': 'OPD timings',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
