# Generated by Django 6.0.4 on 2026-06-13 04:38

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('link_text', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Bibi Kaulan Ji Hospital', max_length=160)),
                ('short_tagline', models.CharField(default='Trusted hospital care for families, OPD consultation, emergency support, and essential medical services.', max_length=220)),
                ('about_short', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('google_maps_embed_url', models.URLField(blank=True)),
                ('main_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('ambulance_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='site/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
