# Generated by Django 6.0.4 on 2026-06-13 05:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='site/og/%Y/%m/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
