# Generated by Django 6.0.4 on 2026-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_meta_description_sitesetting_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('reviewer_name', models.CharField(max_length=120)),
                ('service_context', models.CharField(blank=True, max_length=140)),
                ('review_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video')], default='text', max_length=20)),
                ('quote', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1-5 rating from a verified source.', null=True)),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Publish only after patient/client approval.')),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patient review',
                'verbose_name_plural': 'Patient reviews',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
