# Generated by Django 6.0.4 on 2026-07-17 08:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patientreview_socialfootprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('bkjh', 'Bibi Kaulan Ji Hospital'), ('miri', 'Miri Piri Mission Hospital')], max_length=12, unique=True)),
                ('hospital_name', models.CharField(max_length=160)),
                ('punjabi_name', models.CharField(blank=True, max_length=180)),
                ('short_tagline', models.CharField(blank=True, max_length=240)),
                ('about_short', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('google_maps_embed_url', models.URLField(blank=True)),
                ('main_phone', models.CharField(blank=True, max_length=30)),
                ('call_phone', models.CharField(blank=True, help_text='Number used by public Call Hospital buttons.', max_length=30)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('ambulance_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opd_hours', models.CharField(blank=True, max_length=140)),
                ('emergency_hours', models.CharField(blank=True, max_length=160)),
                ('instagram_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='hospitals/logos/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('static_logo_path', models.CharField(blank=True, help_text='Built-in logo path used when no uploaded logo is available.', max_length=180)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, upload_to='hospitals/og/%Y/%m/', validators=[apps.core.validators.validate_image_file])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital profile',
                'verbose_name_plural': 'Hospital profiles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ParentSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='BKGH Hospitals', max_length=120)),
                ('punjabi_name', models.CharField(blank=True, max_length=160)),
                ('service_area_text', models.CharField(default='Serving families across Fatehgarh Churian, Amritsar, and nearby areas', max_length=220)),
                ('motto_punjabi', models.CharField(blank=True, max_length=160)),
                ('motto_english', models.CharField(default='Service is Our Duty', max_length=120)),
                ('hero_title', models.CharField(default='Two Hospitals. One Trusted Healthcare Network.', max_length=180)),
                ('hero_punjabi', models.CharField(blank=True, max_length=220)),
                ('hero_description', models.TextField(default='Choose the hospital you want to visit for doctors, OPD timings, services, emergency support, and location details.')),
                ('shared_care_title', models.CharField(default='A clearer way for patients to find the right hospital.', max_length=180)),
                ('shared_care_description', models.TextField(default='BKGH Hospitals helps patients choose between Bibi Kaulan Ji Hospital and Miri Piri Mission Hospital before checking services and directions.')),
                ('helpdesk_phone', models.CharField(blank=True, max_length=30)),
                ('meta_title', models.CharField(default='BKGH Hospitals | Bibi Kaulan Ji Hospital & Miri Piri Mission Hospital', max_length=160)),
                ('meta_description', models.CharField(default='BKGH Hospitals connects patients with Bibi Kaulan Ji Hospital and Miri Piri Mission Hospital for OPD timings, doctors, emergency support, services, and location details.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BKGH parent website setting',
                'verbose_name_plural': 'BKGH parent website settings',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
    ]
