# Generated by Django 6.0.4 on 2026-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospitalprofile_parentsitesetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='patientreview',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
    ]
