# Generated by Django 6.0.4 on 2026-07-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='both', max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='both', max_length=12),
        ),
        migrations.AddField(
            model_name='facility',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='both', max_length=12),
        ),
        migrations.AddField(
            model_name='opdtiming',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='both', max_length=12),
        ),
        migrations.AddField(
            model_name='service',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='both', max_length=12),
        ),
    ]
