# Generated by Django 6.0.4 on 2026-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_department_hospital_scope_doctor_hospital_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceinfo',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AddField(
            model_name='emergencyinfo',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AddField(
            model_name='healthcampupdate',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
    ]
