# Generated by Django 6.0.4 on 2026-07-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_ambulanceinfo_hospital_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
