# Generated by Django 6.0.4 on 2026-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_department_image_remove_facility_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='static_photo_path',
            field=models.CharField(blank=True, help_text='Built-in photo path used for approved deployed doctor photos.', max_length=220),
        ),
    ]
