# Generated by Django 6.0.4 on 2026-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctor_static_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulanceinfo',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='emergencyinfo',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='facility',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='healthcampupdate',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='opdtiming',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Shared intentionally across both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
    ]
