# Generated by Django 6.0.4 on 2026-07-17 08:01

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Built-in image path used for deployed gallery photos.', max_length=220),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/%Y/%m/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
