# Generated by Django 6.0.4 on 2026-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='hospital_scope',
            field=models.CharField(choices=[('both', 'Both hospitals'), ('bkjh', 'Bibi Kaulan Ji Hospital only'), ('miri', 'Miri Piri Mission Hospital only')], default='bkjh', max_length=12),
        ),
    ]
