# Generated by Django 6.0.4 on 2026-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentrequest_hospital_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='hospital_scope',
            field=models.CharField(choices=[('bkjh', 'Bibi Kaulan Ji Hospital'), ('miri', 'Miri Piri Mission Hospital')], default='bkjh', max_length=12),
        ),
    ]
